### ISSUE TITLE
getElementById instead of query selector

### ISSUE THREAD

**Issue by Karyum** [facn2/ApolloXI#54]
any reason why the form is the only one thats being called using getElementById and not querySelector?
https://github.com/facn2/ApolloXI/blob/master/public/script.js#L3

**Comment by veredrec** [comment]
@Karyum actually there is no reason. Is it bad practice to use both "querySelector" and "getElementById"?

**Comment by Karyum** [comment]
@veredrec it's just for consistency reasons you have 4 querySelectors and then getById in the middle, i thought theres a different reason for that. but if it's for no reason then better to keep it consistent

**Comment by veredrec** [comment]
@Karyum sounds good. Done :)
