### ISSUE TITLE
merging pull requests without reviews from the whole group

### ISSUE THREAD

**Issue by mattlub** [facn2/ApolloXI#55]
Every pull request I looked at had not been reviewed by the whole group.
A lot were also merged by the creator without review.

This is not a good way to work

**Comment by KatiaAsh** [comment]
@mattlub The only way we find its work with youtube, was to open it on GitHub for testing so we ended up making a lot of pull requests to make this functions works.
and we didn't make a lot of changes to make the whole team reviews.

**Comment by mattlub** [comment]
ok sure- you could have got it working somewhere else, and then added it to the project after. i.e. a 'technical spike'

**Comment by KatiaAsh** [comment]
Yeah we know, we will try to find a way.
