### ISSUE TITLE
display of search results for mobiles is aligned to the left  

### ISSUE THREAD

**Issue by Heathercoraje** [facn2/ApolloXI#64]
![image](https://user-images.githubusercontent.com/25890050/28405904-fdb609ce-6d36-11e7-9d8b-a94d905a36c3.png)

**Comment by rinoma** [comment]
Done

**Comment by rinoma** [comment]
@Heathercoraje close please

**Comment by Heathercoraje** [comment]
It looks much better! closing the issue
