### ISSUE TITLE
Classes for CSS

### ISSUE THREAD

**Issue by matthewdking** [facn2/ApolloXI#66]
Using classes for CSS instead of IDs is good practice as separates your JS and CSS.

**Comment by veredrec** [comment]
@matthewdking I think (and some smart people here agree with me ;) ) that it is more a matter of preference and not wrong/right. I prefer to use "id" when I will use something once but I can definitely understand your view. Anyway, thanks for the comment :)

**Comment by matthewdking** [comment]
@veredrec following our debate. You are right it is down to personal preference.
